apiVersion: v1
kind: Service
metadata:
  name: kafka-service-ext
  labels:
    app: kafka
spec:
  ports:
  - port: {{ .Values.kafka.port }}
    name: kafka-port
    targetPort: {{ .Values.kafka.port }}
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-headless
  labels:
    app: kafka
spec:
  clusterIP: None
  selector:
    app: kafka