apiVersion: v1
kind: Service
metadata:
  name: ksqlserver
  labels:
    app: ksqlserver
spec:
  ports:
  - port: {{ .Values.ksqlserver.port }}
    name: ksqlserver-port
    targetPort: {{ .Values.ksqlserver.port }}
    protocol: TCP
  selector:
    app: ksqlserver