apiVersion: v1
kind: Service
metadata:
  name: schema-service
  labels:
    app: schema
spec:
  ports:
  - port: {{ .Values.schemaregistry.port }}
    name: reg-port
    targetPort: {{ .Values.schemaregistry.port }}
    protocol: TCP
  selector:
    app: schema